### ISSUE TITLE
按照流程来但是报错了

### ISSUE THREAD

**Issue by chenruhai** [MangataTS/kaptreebot#3]
PS E:\Users\Administrator\Desktop\kaptreebot> python bot.py
Traceback (most recent call last):
  File "bot.py", line 4, in <module>
    import nonebot
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\__init__.py", line 138, in <module>
    from .command import CommandSession, CommandGroup
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\command\__init__.py", line 927, in <module>
    from nonebot.command.group import CommandGroup
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\command\group.py", line 3, in <module>
    from nonebot.plugin import on_command
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\plugin\__init__.py", line 17, in <module>
    from nonebot.matcher import Matcher
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\matcher.py", line 15, in <module>
    from nonebot.rule import Rule
  File "C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\rule.py", line 21, in <module>
    from nonebot import get_driver
ImportError: cannot import name 'get_driver' from partially initialized module 'nonebot' (most likely due to a circular import) (C:\Users\Administrator\anaconda3\lib\site-packages\nonebot\__init__.py)

**Comment by MangataTS** [comment]
如果现在您还想使用这个bot的话，您可以看看我最近出的一个教程，之前忙着比赛忘记看issues了，如果您还有问题建议加群询问哦1055277728

**Comment by wjx354** [comment]
[2021-08-29 20:39:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8765/ws
[2021-08-29 20:39:30] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8765/ws 时出现错误: dial tcp 127.0.0.1:8765: connectex: No connection could be made because the target machine actively refused it.

请问这个问题是什么引起的呢

**Comment by MangataTS** [comment]
端口占用感觉是



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月29日(星期天) 晚上8:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3)





 
[2021-08-29 20:39:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8765/ws
 [2021-08-29 20:39:30] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8765/ws 时出现错误: dial tcp 127.0.0.1:8765: connectex: No connection could be made because the target machine actively refused it.
 
请问这个问题是什么引起的呢
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wjx354** [comment]
我更改了很多次端口都是这样，有什么有效的解决办法吗up？我没找到行之有效的措施




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MangataTS/kaptreebot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月29日(星期天) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3)





 端口占用感觉是 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2021年8月29日(星期天) 晚上8:40 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3) 
 
 
 
 
 
   
 [2021-08-29 20:39:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8765/ws 
  [2021-08-29 20:39:30] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8765/ws 时出现错误: dial tcp 127.0.0.1:8765: connectex: No connection could be made because the target machine actively refused it. 
   
 请问这个问题是什么引起的呢 
   
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MangataTS** [comment]
您也可以看看我的一个配置视频，可能是你配置的时候有些文件有点问题
https://www.bilibili.com/video/BV1DP4y1W7ji
或者你可以加群问问噢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月29日(星期天) 晚上8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3)





 我更改了很多次端口都是这样，有什么有效的解决办法吗up？我没找到行之有效的措施 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "MangataTS/kaptreebot"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年8月29日(星期天) 晚上8:50 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3) 
 
 
 
 
 
  端口占用感觉是  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2021年8月29日(星期天) 晚上8:40  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [MangataTS/kaptreebot] 按照流程来但是报错了 (#3)  
   
   
   
   
   
     
  [2021-08-29 20:39:28] [INFO]: 开始尝试连接到反向WebSocket Universal服务器: ws://127.0.0.1:8765/ws  
   [2021-08-29 20:39:30] [WARNING]: 连接到反向WebSocket Universal服务器 ws://127.0.0.1:8765/ws 时出现错误: dial tcp 127.0.0.1:8765: connectex: No connection could be made because the target machine actively refused it.  
     
  请问这个问题是什么引起的呢  
     
  —  
  You are receiving this because you commented.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
  Triage notifications on the go with GitHub Mobile for iOS or Android.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android. 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
